### ISSUE TITLE
找不到文件路径

### ISSUE THREAD

**Issue by 15117271732** [TOWESSL/TOWESSL#1]
if(args.raw=='amazon'):
    raw=['../common_data/amazon/senti_reviews_Electronics_5.txt']
你好，请问这个文件是怎么得来的呀？

**Comment by ValkyriaLenneth** [comment]
您好, 这个文件是由 `data_preprocessing/pre_amazon_yelp_raw.py` 脚本生成的. 它的原始文件请从readme中提供的amazon数据集中下载对应的electronics主题数据. 具体文件路径您可以自定义变更. 因为数据集体量巨大, 我们在处理时大概用了一天的时间.
