### ISSUE TITLE
Can Chinese data sets be used

### ISSUE THREAD

**Issue by Reset-aa** [TOWESSL/TOWESSL#2]
Hello, can this be used for Chinese aspect emotion analysis

**Comment by qianlanwyd** [comment]
Yes,but you should modify the dataloader and model(bert->chinese bert) by yourself.

**Comment by Reset-aa** [comment]
> 是的，但是你应该自己修改数据加载器和模型（bert->chinese bert）。

Thank you. I will use this model as the first step in an aspect level sentiment analysis task in my paper
